language: java
before_install:
  - git clone https://github.com/tunguski/matsuo-core.git
  - cd matsuo-core
  - mvn install
script: mvn package
after_success: mvn cobertura:cobertura; mvn coveralls:report
jdk:
  - openjdk10
